### ISSUE TITLE
Admin Login Page

### ISSUE THREAD

**Issue by securetorobert** [BanTheBad/frontend#1]
We need pages that will let admin users do the following:

- Login

**Comment by NedyUdombat** [comment]
@securetorobert Are you working on this? If not can I take it up and send in a PR today?
cc @Auwalms @sage-godspeed

**Comment by NedyUdombat** [comment]
I have raised a PR to this Issue. The PR only contains the admin login pages as the password reset pages are not designed yet.

https://github.com/BanTheBad/frontend/pull/19

cc @securetorobert @Auwalms @sage-godspeed

**Comment by Auwalms** [comment]
Seen this. I have reviewed and merged. Help and always submit the desktop view of the project as well the mobile view for subsequent PRs. God bless.

**Comment by NedyUdombat** [comment]
@Auwalms Do you suggest we come up with a web view on our own volition, seeing that there are no designs yet for web-view?

The thought I had in mind was to build the mobile view first and then scale up to the web view any time the designs for the web view are ready.

Please what is your take on this?

**Comment by Auwalms** [comment]
oh I get your point then. Let's stick to what's in the design docs then.
